import type { Config } from 'tailwindcss';

export default {
  content: ['packages/react-piano-keyboard/src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        piano: {
          accent: 'var(--piano-accent)',
          'accent-off': 'var(--piano-accent-off)',
          'bg-primary': 'var(--piano-bg-primary)',
          'bg-secondary': 'var(--piano-bg-secondary)',
          'bg-tertiary': 'var(--piano-bg-tertiary)',
          'bg-elevated': 'var(--piano-bg-elevated)',
          'border': 'var(--piano-border)',
          'border-strong': 'var(--piano-border-strong)',
          'text-primary': 'var(--piano-text-primary)',
          'text-secondary': 'var(--piano-text-secondary)',
          'text-muted': 'var(--piano-text-muted)',
          'note-white-bg-top': 'var(--piano-note-white-bg-top)',
          'note-white-bg-bottom': 'var(--piano-note-white-bg-bottom)',
          'note-white-border': 'var(--piano-note-white-border)',
          'note-white-text': 'var(--piano-note-white-text)',
          'note-white-playing-top': 'var(--piano-note-white-playing-top)',
          'note-white-playing-bottom': 'var(--piano-note-white-playing-bottom)',
          'note-white-hover-top': 'var(--piano-note-white-hover-top)',
          'note-white-hover-bottom': 'var(--piano-note-white-hover-bottom)',
          'note-black-bg-from': 'var(--piano-note-black-bg-from)',
          'note-black-bg-to': 'var(--piano-note-black-bg-to)',
          'note-black-text': 'var(--piano-note-black-text)',
          'note-black-playing-from': 'var(--piano-note-black-playing-from)',
          'note-black-playing-to': 'var(--piano-note-black-playing-to)',
          'note-black-hover-from': 'var(--piano-note-black-hover-from)',
          'note-black-hover-to': 'var(--piano-note-black-hover-to)',
          'controls-bg': 'var(--piano-controls-bg)',
          'notes-well-bg': 'var(--piano-notes-well-bg)',
          'waveform-bg': 'var(--piano-waveform-bg)',
          'waveform-container-bg': 'var(--piano-waveform-container-bg)',
          'power-border': 'var(--power-border)',
          'power-bg': 'var(--power-bg)',
          'power-shadow': 'var(--power-shadow)',
          'power-bg-active': 'var(--power-bg-active)',
          'power-shadow-active': 'var(--power-shadow-active)',
        },
      },
      spacing: {
        em: '1em',
        '2em': '2em',
        '3em': '3em',
        '5em': '5em',
        '6em': '6em',
        '7em': '7em',
        '8em': '8em',
        '14em': '14em',
        '16em': '16em',
      },
      boxShadow: {
        'piano-key-white': `-1px 0 0 rgba(255, 255, 255, 0.8) inset,
          0 0 5px #ccc inset,
          0 0 3px rgba(0, 0, 0, 0.2)`,
        'piano-key-white-playing': `2px 0 3px rgba(0, 0, 0, 0.1) inset,
          -5px 5px 20px rgba(0, 0, 0, 0.2) inset,
          0 0 3px rgba(0, 0, 0, 0.2)`,
        'piano-key-black': `-1px -1px 2px rgba(255, 255, 255, 0.2) inset,
          0 -5px 2px 3px rgba(0, 0, 0, 0.6) inset,
          0 2px 4px rgba(0, 0, 0, 0.5)`,
        'piano-key-black-playing': `-1px -1px 2px rgba(255, 255, 255, 0.2) inset,
          0 -2px 2px 3px rgba(0, 0, 0, 0.6) inset,
          0 1px 2px rgba(0, 0, 0, 0.5)`,
        'piano-key-black-hover': `-1px -1px 2px rgba(255, 255, 255, 0.2) inset,
          0 -2px 2px 3px rgba(0, 0, 0, 0.6) inset,
          0 1px 2px rgba(0, 0, 0, 0.5)`,
        'piano-case': '0 5px 15px rgba(0, 0, 0, 0.5)',
      },
      backgroundImage: {
        'piano-white-default': 'linear-gradient(to bottom, var(--piano-note-white-bg-top) 0%, var(--piano-note-white-bg-bottom) 100%)',
        'piano-white-playing': 'linear-gradient(to bottom, var(--piano-note-white-playing-top) 0%, var(--piano-note-white-playing-bottom) 100%)',
        'piano-white-hover': 'linear-gradient(to bottom, var(--piano-note-white-hover-top) 0%, var(--piano-note-white-hover-bottom) 100%)',
        'piano-black-default': 'linear-gradient(45deg, var(--piano-note-black-bg-from) 0%, var(--piano-note-black-bg-to) 100%)',
        'piano-black-playing': 'linear-gradient(to right, var(--piano-note-black-playing-from) 0%, var(--piano-note-black-playing-to) 100%)',
        'piano-black-hover': 'linear-gradient(to right, var(--piano-note-black-hover-from) 0%, var(--piano-note-black-hover-to) 100%)',
        'piano-conflict-white': 'linear-gradient(to bottom, #fca5a5 0%, #f87171 100%)',
        'piano-conflict-black': 'linear-gradient(45deg, #7f1d1d 0%, #dc2626 100%)',
      },
      borderRadius: {
        'piano': '5px',
      },
    },
  },
  plugins: [],
} satisfies Config;
