import type { OscillatorConfig } from "../../../constants";
import type { Audio } from "../../../use-piano/use-music-notes";

export type Preset = {
  name: string;
  opts: Partial<Audio.SetOptions>;
};

export const PRESETS: Preset[] = [
  {
    name: "Default",
    opts: {
      oscillators: [
        { waveform: "sine", gain: 0.5, detune: 0, octave: 0, pan: 0 },
        { waveform: "sine", gain: 0.5, detune: 0, octave: 0, pan: 0 },
      ] satisfies OscillatorConfig[],
      gain: 0.5,
      attack: 0.2,
      decay: 0.4,
      sustain: 0.5,
      release: 0.4,
      filterCutoff: 20000,
      filterResonance: 0.1,
      filterType: "lowpass",
      lfoRate: 4,
      lfoDepth: 0,
      lfoTarget: "none",
      lfoWaveform: "sine",
    },
  },
  {
    name: "Warm Pad",
    opts: {
      oscillators: [
        { waveform: "sawtooth", gain: 0.4, detune: 0, octave: 0, pan: 0 },
        { waveform: "sine", gain: 0.4, detune: 1, octave: 0, pan: 0 },
      ] satisfies OscillatorConfig[],
      gain: 0.4,
      attack: 0.8,
      decay: 0.3,
      sustain: 0.7,
      release: 1.5,
      filterCutoff: 2000,
      filterResonance: 1.5,
      filterType: "lowpass",
      lfoRate: 3,
      lfoDepth: 0.3,
      lfoTarget: "volume",
      lfoWaveform: "sine",
    },
  },
  {
    name: "Filter Sweep",
    opts: {
      oscillators: [
        { waveform: "sawtooth", gain: 0.5, detune: 0, octave: 0, pan: 0 },
        { waveform: "square", gain: 0.3, detune: 0, octave: 0, pan: 0 },
      ] satisfies OscillatorConfig[],
      gain: 0.45,
      attack: 0.05,
      decay: 0.2,
      sustain: 0.4,
      release: 0.8,
      filterCutoff: 500,
      filterResonance: 6,
      filterType: "lowpass",
      lfoRate: 2,
      lfoDepth: 0.5,
      lfoTarget: "filter",
      lfoWaveform: "sine",
    },
  },
  {
    name: "Pluck",
    opts: {
      oscillators: [
        { waveform: "triangle", gain: 0.5, detune: 0, octave: 0, pan: 0 },
        { waveform: "sine", gain: 0.2, detune: 0, octave: 0, pan: 0 },
      ] satisfies OscillatorConfig[],
      gain: 0.5,
      attack: 0.01,
      decay: 0.15,
      sustain: 0,
      release: 0.1,
      filterCutoff: 4000,
      filterResonance: 2,
      filterType: "lowpass",
      lfoRate: 4,
      lfoDepth: 0,
      lfoTarget: "none",
      lfoWaveform: "sine",
    },
  },
  {
    name: "Wobble Bass",
    opts: {
      oscillators: [
        { waveform: "square", gain: 0.5, detune: -100, octave: 0, pan: 0 },
        { waveform: "sawtooth", gain: 0.3, detune: -100, octave: 0, pan: 0 },
      ] satisfies OscillatorConfig[],
      gain: 0.35,
      attack: 0.02,
      decay: 0.1,
      sustain: 0.3,
      release: 0.6,
      filterCutoff: 800,
      filterResonance: 8,
      filterType: "lowpass",
      lfoRate: 6,
      lfoDepth: 0.6,
      lfoTarget: "filter",
      lfoWaveform: "sine",
    },
  },
  {
    name: "Vibrato",
    opts: {
      oscillators: [
        { waveform: "sine", gain: 0.4, detune: 0, octave: 0, pan: 0 },
        { waveform: "triangle", gain: 0.3, detune: 0, octave: 0, pan: 0 },
      ] satisfies OscillatorConfig[],
      gain: 0.4,
      attack: 0.1,
      decay: 0.2,
      sustain: 0.6,
      release: 0.5,
      filterCutoff: 20000,
      filterResonance: 0.1,
      filterType: "lowpass",
      lfoRate: 5,
      lfoDepth: 0.3,
      lfoTarget: "pitch",
      lfoWaveform: "sine",
    },
  },
  {
    name: "Analog Bass",
    opts: {
      oscillators: [
        { waveform: "sawtooth", gain: 0.5, detune: -100, octave: 0, pan: 0 },
        { waveform: "square", gain: 0.3, detune: -100, octave: 0, pan: 0 },
      ] satisfies OscillatorConfig[],
      gain: 0.3,
      attack: 0.01,
      decay: 0.14,
      sustain: 0.04,
      release: 0.14,
      filterCutoff: 728,
      filterResonance: 1,
      filterType: "lowpass",
      lfoRate: 4,
      lfoDepth: 0,
      lfoTarget: "none",
      lfoWaveform: "sine",
    },
  },
  {
    name: "Alien Tongue",
    opts: {
      oscillators: [
        { waveform: "sawtooth", gain: 0.4, detune: 100, octave: 0, pan: 0 },
        { waveform: "sawtooth", gain: 0.3, detune: -100, octave: 0, pan: 0 },
      ] satisfies OscillatorConfig[],
      gain: 0.2,
      attack: 0.01,
      decay: 3.1,
      sustain: 0,
      release: 1.9,
      filterCutoff: 1055,
      filterResonance: 20,
      filterType: "lowpass",
      lfoRate: 4,
      lfoDepth: 0,
      lfoTarget: "none",
      lfoWaveform: "sine",
    },
  },
];
